In [1]:
import geopandas as gpd
import osmnx as ox
import pathlib 
NOTEBOOK_PATH = pathlib.Path().resolve()
DATA_DIRECTORY = NOTEBOOK_PATH / "data"
OUTPUT_DIRECTORY = NOTEBOOK_PATH / "docs"
NOTEBOOK_PATH

PosixPath('/home/jovyan/my-work/practical4')

In [2]:
import geopandas
import pandas as pd
# Statistics Finland WFS
LOUNAISTIETO_WFS_BASE_URL = (
    "https://geoserver.lounaistieto.fi/geoserver/service_points/ows"
    "?service=wfs"
    "&version=2.0.0"
    "&request=GetFeature"
    "&srsName=EPSG:3067"
    "&typeName={layer:s}"
)
# Import layer of schools in Finland
kasvatus_ja_koulutuspalvelut = (
    geopandas.read_file(
        LOUNAISTIETO_WFS_BASE_URL.format(layer="kasvatus_ja_koulutuspalvelut")
    )
    .set_crs("EPSG: 3067")
)
# Select only schools
koulut = kasvatus_ja_koulutuspalvelut[kasvatus_ja_koulutuspalvelut["palvelukohdetyyppi"]=="Koulut (perusopetus)"]
#Select only inside study area
aluerajaus = gpd.read_file(DATA_DIRECTORY/"aluerajaus"/"aluerajaus.shp")
koulut = koulut[koulut.within(aluerajaus.at[0,"geometry"])]
koulut

,gml_id,kohteen_nimi,palvelukohdetyyppi,palvelut,osoite,aukioloajat,verkkosivu,puhelinnumero,sahkoposti,datalahde,orig_id,geometry
3,kasvatus_ja_koulutuspalvelut.499,Wäinö Aaltosen koulun sali,Koulut (perusopetus),"Motionssalar,Bokning av idrottslokaler","Wäinö Aaltosen koulutie 3, 20900 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,+35822535707,-,PTV,e209c1b4-7c22-4ded-aad2-2c21cf34dded,POINT (237111 6706735)
4,kasvatus_ja_koulutuspalvelut.502,Uittamon koulun sali,Koulut (perusopetus),"Motionssalar,Bokning av idrottslokaler","Jalustinkatu 8, 20880 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,+35822535707,-,PTV,d0d32aaa-ef01-4f23-a902-cfbbb50963fb,POINT (239162 6707988)
5,kasvatus_ja_koulutuspalvelut.197,Puolalanmäen koulun yläsali,Koulut (perusopetus),"Motionssalar,Bokning av idrottslokaler","Puutarhakatu 5, 20100 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,-,-,PTV,2f592660-7da0-4869-ac52-ae68a4121417,POINT (239422.984 6711194)
7,kasvatus_ja_koulutuspalvelut.500,"Pansion koulun opiskeluhuolto, Turku",Koulut (perusopetus),"Koulukuraattoripalvelut,Kouluterveydenhuollon ...","Pernontie 29, 20240 TURKU",-,https://www.varha.fi/fi/palvelut/terveysasemap...,+358444910151; +358447276764; +358449012974,-,PTV,4f208e05-7546-4588-9bc7-b490c5f8bb6e,POINT (234346 6711304)
9,kasvatus_ja_koulutuspalvelut.216,Suikkilan koulun sali,Koulut (perusopetus),"Motionssalar,Bokning av idrottslokaler","Talinkorventie 16, 20320 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,+35822535707,-,PTV,485f064d-8ac5-4c7c-9946-692df5cd813e,POINT (237370 6712642)
...,...,...,...,...,...,...,...,...,...,...,...,...
350,kasvatus_ja_koulutuspalvelut.725,"Mikaelin koulun opiskeluhuolto, Turku",Koulut (perusopetus),"Koulukuraattoripalvelut,Kouluterveydenhuollon ...","Luolavuorentie 1 A, 20810 TURKU",-,https://www.varha.fi/fi/palvelut/terveysasemap...,+358406805923; +358405489251; +358406739616,-,PTV,f115ef41-dfd6-4c5d-9d1b-d61ce27778a5,POINT (239939 6709680)
357,kasvatus_ja_koulutuspalvelut.732,Pääskyvuoren koulun sali,Koulut (perusopetus),"Motionssalar,Bokning av idrottslokaler","Talvitie 10, 20610 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,+35822535707,-,PTV,facb2f63-acc0-4854-8fd1-f0fba279b60d,POINT (243495 6709983)
358,kasvatus_ja_koulutuspalvelut.733,Vähä-Heikkilän koulun sali,Koulut (perusopetus),"Motionssalar,Bokning av idrottslokaler","Myllymäentie 42, 20810 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,+35822535707,-,PTV,faf212bc-c614-4f1d-9a74-602e4f2285f4,POINT (238890 6709130)
359,kasvatus_ja_koulutuspalvelut.734,"Mikaelin koulu, Lyseon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Varusmestarintie 19, 20360 TURKU",-,https://blog.edu.turku.fi/mikael/,-,-,PTV,fc8338fb-5998-4c61-9d78-dbbaeec783a6,POINT (240177 6715471)
360,kasvatus_ja_koulutuspalvelut.735,Turun normaalikoulun sali,Koulut (perusopetus),NaN,"Annikanpolku 9, 20610 TURKU",-,https://timmi.turku.fi/WebTimmi/login.do?login...,+35822535707,-,PTV,fde12c1b-b1ce-4e4f-bd3d-62014d84dcce,POINT (244697.125 6710185)

In [3]:
sv = koulut[koulut["palvelut"].str.contains("perusopetus")].copy()
sv

,gml_id,kohteen_nimi,palvelukohdetyyppi,palvelut,osoite,aukioloajat,verkkosivu,puhelinnumero,sahkoposti,datalahde,orig_id,geometry
11,kasvatus_ja_koulutuspalvelut.225,Sirkkala skola,Koulut (perusopetus),Ruotsinkielinen perusopetus,"Sirkkalankatu 20, 20700 TURKU",-,https://blog.edu.turku.fi/sirkkalaskola,-,-,PTV,3d98345e-dc5d-4e12-920b-09bb2e210d4c,POINT (240530 6710393)
13,kasvatus_ja_koulutuspalvelut.252,Topeliuksen koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Pakkarinkatu 10, 20100 TURKU",-,https://blog.edu.turku.fi/topelius/,-,-,PTV,43b9734f-471b-4240-9eca-aa8e72b2a76c,POINT (238090 6710020)
15,kasvatus_ja_koulutuspalvelut.254,"Vähä-Heikkilän koulu, Vähä-Heikkilän yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Myllymäentie 42, 20810 TURKU",-,https://blog.edu.turku.fi/vahaheikkila/,-,-,PTV,a4151726-be04-47ed-bf2a-c5620c03fc41,POINT (238890 6709130)
17,kasvatus_ja_koulutuspalvelut.507,"Vasaramäen koulu, Lemminkäisenkadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Lemminkäisenkatu 30, 3 krs., 20520 TURKU",-,https://blog.edu.turku.fi/vasaramaki/,+3582330000; +3582330000; +3582330000,-,PTV,53b17404-6c03-417f-bbc6-76c01dab7a9a,POINT (241523 6710521)
25,kasvatus_ja_koulutuspalvelut.506,"Nummenpakan koulu, Halisten yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Paavinkatu 13, 20540 TURKU",-,https://blog.edu.turku.fi/nummenpakka/,-,-,PTV,538314fc-40e3-4e69-b70b-0816d903c57d,POINT (242567 6713017)
28,kasvatus_ja_koulutuspalvelut.393,"Kiinamyllyn koulu, nuorisopsykiatrian yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus","Kunnallissairaalantie 20, talo 4 B, 2. krs, PL...",-,http://blog.edu.turku.fi/kiinamylly/,-,-,PTV,020550d6-5532-405a-ae8c-972fd3e8be8d,POINT (240310 6709718)
32,kasvatus_ja_koulutuspalvelut.397,"Turun Lyseon koulu, Kärsämäen yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Kärsämäentie 46, 20360 TURKU",-,https://blog.edu.turku.fi/karsamaki/,-,-,PTV,05906b55-6c4b-43e0-b0f3-828528aaac38,POINT (241119 6714372)
43,kasvatus_ja_koulutuspalvelut.407,Haarlan koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Meteorikatu 1, 20900 TURKU",-,https://blog.edu.turku.fi/haarla,-,-,PTV,10d65f02-e6b2-486d-a5de-250ea20163ba,POINT (236611 6704848)
44,kasvatus_ja_koulutuspalvelut.408,"Luolavuoren koulu, Raadinkadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Raadinkatu 7, D-rak., 20750 TURKU",-,https://blog.edu.turku.fi/luolavuori/yhteystie...,-,-,PTV,10ff296e-c6fd-4175-b3e8-7636327a79c9,POINT (244708 6708507)
53,kasvatus_ja_koulutuspalvelut.417,Puropellon koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Sepänkatu 11, 20700 TURKU",-,https://blog.edu.turku.fi/puris/,-,-,PTV,158943c9-5d62-4324-b611-c7e22eecbdef,POINT (239950 6709886)
65,kasvatus_ja_koulutuspalvelut.429,"Mikaelin koulu, Koulukadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Koulukatu 8, 20100 TURKU",-,https://blog.edu.turku.fi/mikael,-,-,PTV,1c12c6f6-7701-424f-88f7-afa800f6c6f0,POINT (238990 6710649)
77,kasvatus_ja_koulutuspalvelut.442,"Raunistulan koulu, Kähärin yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Pietari Valdin katu 14, 20100 TURKU",-,-,-,-,PTV,20d6ed45-5af1-4f4e-b0d5-fa4707081714,POINT (238715 6711763)
112,kasvatus_ja_koulutuspalvelut.477,"Luostarivuoren koulu, Kerttulin yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Kellonsoittajankatu 6, 20500 TURKU",-,https://blog.edu.turku.fi/martti/kerttuli/,-,-,PTV,3d33c276-4633-4863-829f-2e8095c3612e,POINT (240700 6710724)
117,kasvatus_ja_koulutuspalvelut.483,Rieskalähteen koulu,Koulut (perusopetus),"Henkilökohtainen taideohjaus,Perusopetuksen er...","Jöllintie 3, 20300 TURKU",-,https://blog.edu.turku.fi/rieskalahteenkoulu/,-,-,PTV,46ec0e12-a1f6-4392-9cbd-182165767c19,POINT (239428 6712751)
124,kasvatus_ja_koulutuspalvelut.491,"Turun Lyseon koulu, Pallivahan yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Paltankatu 4, 20360 TURKU",-,https://blog.edu.turku.fi/karsamaki/,-,-,PTV,4b379809-5660-44bf-b874-b6839d693bfc,POINT (240551 6714563)
131,kasvatus_ja_koulutuspalvelut.498,"Luolavuoren koulu, Piiparinpolun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Piiparinpolku 3, 20360 TURKU",-,https://blog.edu.turku.fi/luolavuori/,-,-,PTV,4e6a6615-8966-491e-818e-9b65c874e5cb,POINT (239406 6715041)
133,kasvatus_ja_koulutuspalvelut.511,Jäkärlän koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Kärsämäentie 11 2. krs, 20360 TURKU",-,https://blog.edu.turku.fi/jakarla/,-,-,PTV,54720380-f1e9-4911-8a30-43c90c0604e6,POINT (240994 6713973)
134,kasvatus_ja_koulutuspalvelut.512,"Kiinamyllyn koulu, Datacityn yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus","Lemminkäisenkatu 18 C, 20520 TURKU",-,https://blog.edu.turku.fi/kiinamylly/,-,-,PTV,547b70cb-28a3-4abe-9931-7fec7c56db73,POINT (241281 6710562)
141,kasvatus_ja_koulutuspalvelut.519,"Teräsrautelan koulu, Suikkilan yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Korkkisvuorenkatu 14, 20320 TURKU",-,https://blog.edu.turku.fi/terasrautelankoulu,-,-,PTV,5c237043-0751-4a86-9abe-b209d06ac209,POINT (237931 6713286)
148,kasvatus_ja_koulutuspalvelut.526,Ilpoisten koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Lauklähteenkatu 13, 20740 TURKU",-,https://blog.edu.turku.fi/ilpoinen/,-,-,PTV,636b5c01-e84e-4251-b463-8d2746a55f0c,POINT (240438 6707989)
157,kasvatus_ja_koulutuspalvelut.535,Hepokullan koulu,Koulut (perusopetus),"Perusopetukseen valmistava opetus (VALMO),Suom...","Varkkavuorenkatu 42, 20320 TURKU",-,https://blog.edu.turku.fi/hepokulta/,-,-,PTV,68a03920-136c-48dd-881f-8b5ac1aafd84,POINT (238854 6713900)
169,kasvatus_ja_koulutuspalvelut.547,"Nummenpakan koulu, Nummen yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Paavinkatu 13, 20540 TURKU",-,https://blog.edu.turku.fi/nummenpakka/,-,-,PTV,6f0d0268-145d-41fd-b137-9eabb4e4efb6,POINT (242567 6713017)
174,kasvatus_ja_koulutuspalvelut.552,"Vasaramäen koulu, Lehmustien yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Lehmustie 7, 20720 TURKU",-,https://blog.edu.turku.fi/vasaramaki/,-,-,PTV,73e86bf3-b758-4b75-a68b-7228a27d20ad,POINT (241305 6709342)
186,kasvatus_ja_koulutuspalvelut.564,Katariinan koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Kirkkotie 31, 20540 TURKU",-,https://blog.edu.turku.fi/katariina/,-,-,PTV,7cb51f29-0c86-4157-9945-92eb896a56f1,POINT (241380 6712059)
189,kasvatus_ja_koulutuspalvelut.567,Varissuon koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetukseen val...","Kuopuksenpolku , 20520 TURKU",-,https://blog.edu.turku.fi/varissuonkoulu/,-,-,PTV,80e3c504-40d5-416a-8c7d-c0cfad8c0f9a,POINT (244762 6710036)
193,kasvatus_ja_koulutuspalvelut.571,"Luolavuoren koulu, Ruiskadun yksikkö (pienluokat)",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Ruiskatu 8, 20720 TURKU",-,https://blog.edu.turku.fi/luolavuori/,-,-,PTV,82ccf15a-6c4f-4b61-9d10-41b372c2a448,POINT (241211 6708557)
199,kasvatus_ja_koulutuspalvelut.576,"Vähä-Heikkilän koulu, Uittamon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Jalustinkatu 8, 20880 TURKU",-,https://blog.edu.turku.fi/vahaheikkila/,-,-,PTV,84ce43e4-6ad4-44f2-9252-f615c3bd67bb,POINT (239162 6707988)
203,kasvatus_ja_koulutuspalvelut.580,Pääskyvuoren koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Talvitie 10, 20610 TURKU",-,https://blog.edu.turku.fi/paaskyvuori/,-,-,PTV,9ef8c7ca-b3b5-4e75-af55-5f053203db69,POINT (243495 6709983)
226,kasvatus_ja_koulutuspalvelut.602,"Raunistulan koulu, Raunistulan yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Oikotie 1, 20300 TURKU",Monday: 08:00:00-15:00:00; Tuesday: 08:00:00-1...,https://blog.edu.turku.fi/raunistula/,-,-,PTV,95f31b1b-bbe3-405a-bb6f-609ffdc7668c,POINT (239740 6712307)
229,kasvatus_ja_koulutuspalvelut.605,"Mikaelin koulu, Jopo-yksikkö",Koulut (perusopetus),"Oppilaanohjaus,Joustava perusopetus (JOPO)","Luolavuorentie 1A, 20810 TURKU",-,https://blog.edu.turku.fi/mikael,-,-,PTV,96bf8435-16f2-4fb9-b3d5-63500785c70f,POINT (239933 6709748)
232,kasvatus_ja_koulutuspalvelut.608,"Nummenpakan koulu, Aurajoen yksikkö",Koulut (perusopetus),"Henkilökohtainen taideohjaus,Suomenkielinen pe...","Papinkatu 4, 20540 TURKU",-,https://blog.edu.turku.fi/nummenpakka/,-,-,PTV,a06207fc-745f-40fc-9a04-10edf84248e7,POINT (241497 6712112)
239,kasvatus_ja_koulutuspalvelut.615,"Luostarivuoren koulu, Martin yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Hopeasepänkuja 2, 20810 TURKU",-,https://blog.edu.turku.fi/martti/,-,-,PTV,9b0f5506-9142-4629-b151-5699e8987322,POINT (239309 6709910)
256,kasvatus_ja_koulutuspalvelut.632,"Teräsrautelan koulu, Teräsrautelan yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Korkkisvuorenkatu 14, 20320 TURKU",-,https://blog.edu.turku.fi/terasrautelankoulu,-,-,PTV,af68682c-7f93-4711-aa51-991497b9300d,POINT (237931 6713286)
261,kasvatus_ja_koulutuspalvelut.637,"Luolavuoren koulu, Ruiskadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Ruiskatu 8, 20720 TURKU",-,https://blog.edu.turku.fi/luolavuori/,-,-,PTV,b3559e85-dea6-49eb-bf84-0f51a7760c7e,POINT (241211 6708557)
262,kasvatus_ja_koulutuspalvelut.638,"Turun Lyseon koulu, Runosmäen yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Varusmestarintie 19, 20360 TURKU",-,https://blog.edu.turku.fi/lyseo/,-,-,PTV,b49dc0d5-5b0e-4a68-95cd-fce89e47507f,POINT (240177 6715471)
265,kasvatus_ja_koulutuspalvelut.641,"Katariinan koulu, Halisten yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Paavinkatu 13, rak. A, 20540 TURKU",-,https://blog.edu.turku.fi/katariina/,-,-,PTV,b856abb9-d15f-4270-b37e-11721c832367,POINT (242567 6713017)
273,kasvatus_ja_koulutuspalvelut.649,"Vasaramäen koulu, Puistokoulun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Puolukkatie 11, 20720 TURKU",-,https://blog.edu.turku.fi/vasaramaki/,-,-,PTV,bc7ec3c3-4cb7-41f4-9d61-6ecfab1d18be,POINT (241685 6709840)
281,kasvatus_ja_koulutuspalvelut.657,Lausteen koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Raadinkatu 7, 20750 TURKU",-,https://blog.edu.turku.fi/lauste,-,-,PTV,c1da95bc-9d9f-478f-ad88-91d0ab6bbd81,POINT (244708 6708507)
282,kasvatus_ja_koulutuspalvelut.658,Wäinö Aaltosen koulu,Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Wäinö Aaltosen koulutie 3, 20900 TURKU",-,https://blog.edu.turku.fi/wa,-,-,PTV,c22a005e-8b41-4ba4-847b-2b5365ac255c,POINT (237111 6706735)
285,kasvatus_ja_koulutuspalvelut.660,"Puolalan koulu, Puutarhakadun yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Puutarhakatu 5, 20100 TURKU",-,https://blog.edu.turku.fi/puolala,-,-,PTV,d41240e5-3f09-4746-b108-ba57c499f226,POINT (239424 6711207)
288,kasvatus_ja_koulutuspalvelut.663,Pansion koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Pernontie 29, 20240 TURKU",-,https://blog.edu.turku.fi/pansio/,-,-,PTV,c2f6b4a8-ac24-40d8-a0de-1b988eac08a0,POINT (234346 6711304)
290,kasvatus_ja_koulutuspalvelut.665,"Puolalan koulu, Kauppiaskadun yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Kauppiaskatu 14, 20100 TURKU",-,https://blog.edu.turku.fi/puolala,-,-,PTV,c3c6bea4-3218-431c-823b-a093682a6aa1,POINT (239632 6711361)
292,kasvatus_ja_koulutuspalvelut.667,Aunelan koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetukseen val...","Opintie 1, 20210 TURKU",-,https://blog.edu.turku.fi/aunela/,-,-,PTV,c65ba803-f474-40e3-991c-d449a521fa77,POINT (236163 6711922)
317,kasvatus_ja_koulutuspalvelut.692,S:t Olofsskolan,Koulut (perusopetus),"Perusopetuksen erikoisluokat,Ruotsinkielinen p...","Sirkkalankatu 39, 20700 TURKU",-,https://blog.edu.turku.fi/stolofsskolan/,+3582330000,-,PTV,db2e86d9-4e1e-41cb-9381-80c102435cc7,POINT (239805 6710221)
329,kasvatus_ja_koulutuspalvelut.704,"Luostarivuoren koulu, Luostarivuoren yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Luostarinkatu 13, 20700 TURKU",-,http://blog.edu.turku.fi/luostarivuori,-,-,PTV,e11e97ff-f9e8-4094-9dc0-42f1a55e1959,POINT (239871 6710362)
332,kasvatus_ja_koulutuspalvelut.707,Cygnaeus skola,Koulut (perusopetus),Ruotsinkielinen perusopetus,"Maariankatu 7, 20100 TURKU",-,https://blog.edu.turku.fi/cygnaeus,-,-,PTV,e337afdb-ad64-4b58-8171-7540022d64fa,POINT (239598 6711255)
340,kasvatus_ja_koulutuspalvelut.715,"Hannunniitun koulu, Hannunniitun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Virmuntie 3, 20540 TURKU",-,https://blog.edu.turku.fi/hannunniittu/,-,-,PTV,e9407b73-3d2f-4a68-8a76-9752c95cad84,POINT (242972 6711487)
341,kasvatus_ja_koulutuspalvelut.716,"Mikaelin koulu, Urheilupuiston yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Luolavuorentie 1A, 20520 TURKU",-,https://blog.edu.turku.fi/mikael,-,-,PTV,e945d58b-c2f8-43d7-9cda-92ba7d609498,POINT (239933 6709748)
346,kasvatus_ja_koulutuspalvelut.721,"Hannunniitun koulu, Kohmon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Ritavuorenkuja 6, 20540 TURKU",-,http://blog.edu.turku.fi/hannunniittu/,-,-,PTV,edaa585e-896e-4875-85d6-7c921c2528c2,POINT (244204 6711467)
359,kasvatus_ja_koulutuspalvelut.734,"Mikaelin koulu, Lyseon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Varusmestarintie 19, 20360 TURKU",-,https://blog.edu.turku.fi/mikael/,-,-,PTV,fc8338fb-5998-4c61-9d78-dbbaeec783a6,POINT (240177 6715471)

In [4]:
peruskoulut = koulut[koulut["palvelut"].str.contains("Perusopetus")].copy()
peruskoulut
kaikki_koulut = pd.concat([peruskoulut, sv])
kaikki_koulut.sort_values("kohteen_nimi")

,gml_id,kohteen_nimi,palvelukohdetyyppi,palvelut,osoite,aukioloajat,verkkosivu,puhelinnumero,sahkoposti,datalahde,orig_id,geometry
292,kasvatus_ja_koulutuspalvelut.667,Aunelan koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetukseen val...","Opintie 1, 20210 TURKU",-,https://blog.edu.turku.fi/aunela/,-,-,PTV,c65ba803-f474-40e3-991c-d449a521fa77,POINT (236163 6711922)
332,kasvatus_ja_koulutuspalvelut.707,Cygnaeus skola,Koulut (perusopetus),Ruotsinkielinen perusopetus,"Maariankatu 7, 20100 TURKU",-,https://blog.edu.turku.fi/cygnaeus,-,-,PTV,e337afdb-ad64-4b58-8171-7540022d64fa,POINT (239598 6711255)
43,kasvatus_ja_koulutuspalvelut.407,Haarlan koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Meteorikatu 1, 20900 TURKU",-,https://blog.edu.turku.fi/haarla,-,-,PTV,10d65f02-e6b2-486d-a5de-250ea20163ba,POINT (236611 6704848)
340,kasvatus_ja_koulutuspalvelut.715,"Hannunniitun koulu, Hannunniitun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Virmuntie 3, 20540 TURKU",-,https://blog.edu.turku.fi/hannunniittu/,-,-,PTV,e9407b73-3d2f-4a68-8a76-9752c95cad84,POINT (242972 6711487)
346,kasvatus_ja_koulutuspalvelut.721,"Hannunniitun koulu, Kohmon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Ritavuorenkuja 6, 20540 TURKU",-,http://blog.edu.turku.fi/hannunniittu/,-,-,PTV,edaa585e-896e-4875-85d6-7c921c2528c2,POINT (244204 6711467)
157,kasvatus_ja_koulutuspalvelut.535,Hepokullan koulu,Koulut (perusopetus),"Perusopetukseen valmistava opetus (VALMO),Suom...","Varkkavuorenkatu 42, 20320 TURKU",-,https://blog.edu.turku.fi/hepokulta/,-,-,PTV,68a03920-136c-48dd-881f-8b5ac1aafd84,POINT (238854 6713900)
148,kasvatus_ja_koulutuspalvelut.526,Ilpoisten koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Lauklähteenkatu 13, 20740 TURKU",-,https://blog.edu.turku.fi/ilpoinen/,-,-,PTV,636b5c01-e84e-4251-b463-8d2746a55f0c,POINT (240438 6707989)
133,kasvatus_ja_koulutuspalvelut.511,Jäkärlän koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Kärsämäentie 11 2. krs, 20360 TURKU",-,https://blog.edu.turku.fi/jakarla/,-,-,PTV,54720380-f1e9-4911-8a30-43c90c0604e6,POINT (240994 6713973)
186,kasvatus_ja_koulutuspalvelut.564,Katariinan koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Kirkkotie 31, 20540 TURKU",-,https://blog.edu.turku.fi/katariina/,-,-,PTV,7cb51f29-0c86-4157-9945-92eb896a56f1,POINT (241380 6712059)
265,kasvatus_ja_koulutuspalvelut.641,"Katariinan koulu, Halisten yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Paavinkatu 13, rak. A, 20540 TURKU",-,https://blog.edu.turku.fi/katariina/,-,-,PTV,b856abb9-d15f-4270-b37e-11721c832367,POINT (242567 6713017)
134,kasvatus_ja_koulutuspalvelut.512,"Kiinamyllyn koulu, Datacityn yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus","Lemminkäisenkatu 18 C, 20520 TURKU",-,https://blog.edu.turku.fi/kiinamylly/,-,-,PTV,547b70cb-28a3-4abe-9931-7fec7c56db73,POINT (241281 6710562)
28,kasvatus_ja_koulutuspalvelut.393,"Kiinamyllyn koulu, nuorisopsykiatrian yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus","Kunnallissairaalantie 20, talo 4 B, 2. krs, PL...",-,http://blog.edu.turku.fi/kiinamylly/,-,-,PTV,020550d6-5532-405a-ae8c-972fd3e8be8d,POINT (240310 6709718)
281,kasvatus_ja_koulutuspalvelut.657,Lausteen koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Raadinkatu 7, 20750 TURKU",-,https://blog.edu.turku.fi/lauste,-,-,PTV,c1da95bc-9d9f-478f-ad88-91d0ab6bbd81,POINT (244708 6708507)
131,kasvatus_ja_koulutuspalvelut.498,"Luolavuoren koulu, Piiparinpolun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Piiparinpolku 3, 20360 TURKU",-,https://blog.edu.turku.fi/luolavuori/,-,-,PTV,4e6a6615-8966-491e-818e-9b65c874e5cb,POINT (239406 6715041)
44,kasvatus_ja_koulutuspalvelut.408,"Luolavuoren koulu, Raadinkadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Raadinkatu 7, D-rak., 20750 TURKU",-,https://blog.edu.turku.fi/luolavuori/yhteystie...,-,-,PTV,10ff296e-c6fd-4175-b3e8-7636327a79c9,POINT (244708 6708507)
261,kasvatus_ja_koulutuspalvelut.637,"Luolavuoren koulu, Ruiskadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Ruiskatu 8, 20720 TURKU",-,https://blog.edu.turku.fi/luolavuori/,-,-,PTV,b3559e85-dea6-49eb-bf84-0f51a7760c7e,POINT (241211 6708557)
193,kasvatus_ja_koulutuspalvelut.571,"Luolavuoren koulu, Ruiskadun yksikkö (pienluokat)",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Ruiskatu 8, 20720 TURKU",-,https://blog.edu.turku.fi/luolavuori/,-,-,PTV,82ccf15a-6c4f-4b61-9d10-41b372c2a448,POINT (241211 6708557)
112,kasvatus_ja_koulutuspalvelut.477,"Luostarivuoren koulu, Kerttulin yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Kellonsoittajankatu 6, 20500 TURKU",-,https://blog.edu.turku.fi/martti/kerttuli/,-,-,PTV,3d33c276-4633-4863-829f-2e8095c3612e,POINT (240700 6710724)
329,kasvatus_ja_koulutuspalvelut.704,"Luostarivuoren koulu, Luostarivuoren yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Luostarinkatu 13, 20700 TURKU",-,http://blog.edu.turku.fi/luostarivuori,-,-,PTV,e11e97ff-f9e8-4094-9dc0-42f1a55e1959,POINT (239871 6710362)
239,kasvatus_ja_koulutuspalvelut.615,"Luostarivuoren koulu, Martin yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Hopeasepänkuja 2, 20810 TURKU",-,https://blog.edu.turku.fi/martti/,-,-,PTV,9b0f5506-9142-4629-b151-5699e8987322,POINT (239309 6709910)
229,kasvatus_ja_koulutuspalvelut.605,"Mikaelin koulu, Jopo-yksikkö",Koulut (perusopetus),"Oppilaanohjaus,Joustava perusopetus (JOPO)","Luolavuorentie 1A, 20810 TURKU",-,https://blog.edu.turku.fi/mikael,-,-,PTV,96bf8435-16f2-4fb9-b3d5-63500785c70f,POINT (239933 6709748)
65,kasvatus_ja_koulutuspalvelut.429,"Mikaelin koulu, Koulukadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Koulukatu 8, 20100 TURKU",-,https://blog.edu.turku.fi/mikael,-,-,PTV,1c12c6f6-7701-424f-88f7-afa800f6c6f0,POINT (238990 6710649)
359,kasvatus_ja_koulutuspalvelut.734,"Mikaelin koulu, Lyseon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Varusmestarintie 19, 20360 TURKU",-,https://blog.edu.turku.fi/mikael/,-,-,PTV,fc8338fb-5998-4c61-9d78-dbbaeec783a6,POINT (240177 6715471)
341,kasvatus_ja_koulutuspalvelut.716,"Mikaelin koulu, Urheilupuiston yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Luolavuorentie 1A, 20520 TURKU",-,https://blog.edu.turku.fi/mikael,-,-,PTV,e945d58b-c2f8-43d7-9cda-92ba7d609498,POINT (239933 6709748)
232,kasvatus_ja_koulutuspalvelut.608,"Nummenpakan koulu, Aurajoen yksikkö",Koulut (perusopetus),"Henkilökohtainen taideohjaus,Suomenkielinen pe...","Papinkatu 4, 20540 TURKU",-,https://blog.edu.turku.fi/nummenpakka/,-,-,PTV,a06207fc-745f-40fc-9a04-10edf84248e7,POINT (241497 6712112)
25,kasvatus_ja_koulutuspalvelut.506,"Nummenpakan koulu, Halisten yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Paavinkatu 13, 20540 TURKU",-,https://blog.edu.turku.fi/nummenpakka/,-,-,PTV,538314fc-40e3-4e69-b70b-0816d903c57d,POINT (242567 6713017)
169,kasvatus_ja_koulutuspalvelut.547,"Nummenpakan koulu, Nummen yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Paavinkatu 13, 20540 TURKU",-,https://blog.edu.turku.fi/nummenpakka/,-,-,PTV,6f0d0268-145d-41fd-b137-9eabb4e4efb6,POINT (242567 6713017)
288,kasvatus_ja_koulutuspalvelut.663,Pansion koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Pernontie 29, 20240 TURKU",-,https://blog.edu.turku.fi/pansio/,-,-,PTV,c2f6b4a8-ac24-40d8-a0de-1b988eac08a0,POINT (234346 6711304)
290,kasvatus_ja_koulutuspalvelut.665,"Puolalan koulu, Kauppiaskadun yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Kauppiaskatu 14, 20100 TURKU",-,https://blog.edu.turku.fi/puolala,-,-,PTV,c3c6bea4-3218-431c-823b-a093682a6aa1,POINT (239632 6711361)
285,kasvatus_ja_koulutuspalvelut.660,"Puolalan koulu, Puutarhakadun yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Puutarhakatu 5, 20100 TURKU",-,https://blog.edu.turku.fi/puolala,-,-,PTV,d41240e5-3f09-4746-b108-ba57c499f226,POINT (239424 6711207)
53,kasvatus_ja_koulutuspalvelut.417,Puropellon koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Sepänkatu 11, 20700 TURKU",-,https://blog.edu.turku.fi/puris/,-,-,PTV,158943c9-5d62-4324-b611-c7e22eecbdef,POINT (239950 6709886)
203,kasvatus_ja_koulutuspalvelut.580,Pääskyvuoren koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Talvitie 10, 20610 TURKU",-,https://blog.edu.turku.fi/paaskyvuori/,-,-,PTV,9ef8c7ca-b3b5-4e75-af55-5f053203db69,POINT (243495 6709983)
77,kasvatus_ja_koulutuspalvelut.442,"Raunistulan koulu, Kähärin yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Pietari Valdin katu 14, 20100 TURKU",-,-,-,-,PTV,20d6ed45-5af1-4f4e-b0d5-fa4707081714,POINT (238715 6711763)
226,kasvatus_ja_koulutuspalvelut.602,"Raunistulan koulu, Raunistulan yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Oikotie 1, 20300 TURKU",Monday: 08:00:00-15:00:00; Tuesday: 08:00:00-1...,https://blog.edu.turku.fi/raunistula/,-,-,PTV,95f31b1b-bbe3-405a-bb6f-609ffdc7668c,POINT (239740 6712307)
117,kasvatus_ja_koulutuspalvelut.483,Rieskalähteen koulu,Koulut (perusopetus),"Henkilökohtainen taideohjaus,Perusopetuksen er...","Jöllintie 3, 20300 TURKU",-,https://blog.edu.turku.fi/rieskalahteenkoulu/,-,-,PTV,46ec0e12-a1f6-4392-9cbd-182165767c19,POINT (239428 6712751)
317,kasvatus_ja_koulutuspalvelut.692,S:t Olofsskolan,Koulut (perusopetus),"Perusopetuksen erikoisluokat,Ruotsinkielinen p...","Sirkkalankatu 39, 20700 TURKU",-,https://blog.edu.turku.fi/stolofsskolan/,+3582330000,-,PTV,db2e86d9-4e1e-41cb-9381-80c102435cc7,POINT (239805 6710221)
11,kasvatus_ja_koulutuspalvelut.225,Sirkkala skola,Koulut (perusopetus),Ruotsinkielinen perusopetus,"Sirkkalankatu 20, 20700 TURKU",-,https://blog.edu.turku.fi/sirkkalaskola,-,-,PTV,3d98345e-dc5d-4e12-920b-09bb2e210d4c,POINT (240530 6710393)
141,kasvatus_ja_koulutuspalvelut.519,"Teräsrautelan koulu, Suikkilan yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Korkkisvuorenkatu 14, 20320 TURKU",-,https://blog.edu.turku.fi/terasrautelankoulu,-,-,PTV,5c237043-0751-4a86-9abe-b209d06ac209,POINT (237931 6713286)
256,kasvatus_ja_koulutuspalvelut.632,"Teräsrautelan koulu, Teräsrautelan yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Korkkisvuorenkatu 14, 20320 TURKU",-,https://blog.edu.turku.fi/terasrautelankoulu,-,-,PTV,af68682c-7f93-4711-aa51-991497b9300d,POINT (237931 6713286)
13,kasvatus_ja_koulutuspalvelut.252,Topeliuksen koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Pakkarinkatu 10, 20100 TURKU",-,https://blog.edu.turku.fi/topelius/,-,-,PTV,43b9734f-471b-4240-9eca-aa8e72b2a76c,POINT (238090 6710020)
32,kasvatus_ja_koulutuspalvelut.397,"Turun Lyseon koulu, Kärsämäen yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Kärsämäentie 46, 20360 TURKU",-,https://blog.edu.turku.fi/karsamaki/,-,-,PTV,05906b55-6c4b-43e0-b0f3-828528aaac38,POINT (241119 6714372)
124,kasvatus_ja_koulutuspalvelut.491,"Turun Lyseon koulu, Pallivahan yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Paltankatu 4, 20360 TURKU",-,https://blog.edu.turku.fi/karsamaki/,-,-,PTV,4b379809-5660-44bf-b874-b6839d693bfc,POINT (240551 6714563)
262,kasvatus_ja_koulutuspalvelut.638,"Turun Lyseon koulu, Runosmäen yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Varusmestarintie 19, 20360 TURKU",-,https://blog.edu.turku.fi/lyseo/,-,-,PTV,b49dc0d5-5b0e-4a68-95cd-fce89e47507f,POINT (240177 6715471)
189,kasvatus_ja_koulutuspalvelut.567,Varissuon koulu,Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetukseen val...","Kuopuksenpolku , 20520 TURKU",-,https://blog.edu.turku.fi/varissuonkoulu/,-,-,PTV,80e3c504-40d5-416a-8c7d-c0cfad8c0f9a,POINT (244762 6710036)
174,kasvatus_ja_koulutuspalvelut.552,"Vasaramäen koulu, Lehmustien yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Lehmustie 7, 20720 TURKU",-,https://blog.edu.turku.fi/vasaramaki/,-,-,PTV,73e86bf3-b758-4b75-a68b-7228a27d20ad,POINT (241305 6709342)
17,kasvatus_ja_koulutuspalvelut.507,"Vasaramäen koulu, Lemminkäisenkadun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Lemminkäisenkatu 30, 3 krs., 20520 TURKU",-,https://blog.edu.turku.fi/vasaramaki/,+3582330000; +3582330000; +3582330000,-,PTV,53b17404-6c03-417f-bbc6-76c01dab7a9a,POINT (241523 6710521)
273,kasvatus_ja_koulutuspalvelut.649,"Vasaramäen koulu, Puistokoulun yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Oppilaanohjaus,Peru...","Puolukkatie 11, 20720 TURKU",-,https://blog.edu.turku.fi/vasaramaki/,-,-,PTV,bc7ec3c3-4cb7-41f4-9d61-6ecfab1d18be,POINT (241685 6709840)
199,kasvatus_ja_koulutuspalvelut.576,"Vähä-Heikkilän koulu, Uittamon yksikkö",Koulut (perusopetus),"Suomenkielinen perusopetus,Perusopetuksen aamu...","Jalustinkatu 8, 20880 TURKU",-,https://blog.edu.turku.fi/vahaheikkila/,-,-,PTV,84ce43e4-6ad4-44f2-9252-f615c3bd67bb,POINT (239162 6707988)
15,kasvatus_ja_koulutuspalvelut.254,"Vähä-Heikkilän koulu, Vähä-Heikkilän yksikkö",Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Myllymäentie 42, 20810 TURKU",-,https://blog.edu.turku.fi/vahaheikkila/,-,-,PTV,a4151726-be04-47ed-bf2a-c5620c03fc41,POINT (238890 6709130)
282,kasvatus_ja_koulutuspalvelut.658,Wäinö Aaltosen koulu,Koulut (perusopetus),"Perusopetuksen erikoisluokat,Suomenkielinen pe...","Wäinö Aaltosen koulutie 3, 20900 TURKU",-,https://blog.edu.turku.fi/wa,-,-,PTV,c22a005e-8b41-4ba4-847b-2b5365ac255c,POINT (237111 6706735)

In [5]:
turku_koulut = kaikki_koulut[kaikki_koulut["osoite"].str.contains("TURKU")].copy()

In [6]:
# Some rows have same point locaiton but different school yksikkö. 
# group schools by their coordinates and combine their names
turku_koulut["geometry_id"] = turku_koulut.geometry.to_wkt()
schools_combined = turku_koulut.dissolve(
    by="geometry_id",
    aggfunc={
        "kohteen_nimi": lambda x: ", ".join(x),
        "osoite": "first",
        "palvelut": "first"
    },
    as_index=False
).sort_values("kohteen_nimi")

In [7]:
schools_combined

,geometry_id,geometry,kohteen_nimi,osoite,palvelut
1,POINT (236163 6711922),POINT (236163 6711922),Aunelan koulu,"Opintie 1, 20210 TURKU","Suomenkielinen perusopetus,Perusopetukseen val..."
15,POINT (239598 6711255),POINT (239598 6711255),Cygnaeus skola,"Maariankatu 7, 20100 TURKU",Ruotsinkielinen perusopetus
2,POINT (236611 6704848),POINT (236611 6704848),Haarlan koulu,"Meteorikatu 1, 20900 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
38,POINT (242972 6711487),POINT (242972 6711487),"Hannunniitun koulu, Hannunniitun yksikkö","Virmuntie 3, 20540 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
40,POINT (244204 6711467),POINT (244204 6711467),"Hannunniitun koulu, Kohmon yksikkö","Ritavuorenkuja 6, 20540 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
7,POINT (238854 6713900),POINT (238854 6713900),Hepokullan koulu,"Varkkavuorenkatu 42, 20320 TURKU","Perusopetukseen valmistava opetus (VALMO),Suom..."
24,POINT (240438 6707989),POINT (240438 6707989),Ilpoisten koulu,"Lauklähteenkatu 13, 20740 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
28,POINT (240994 6713973),POINT (240994 6713973),Jäkärlän koulu,"Kärsämäentie 11 2. krs, 20360 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
33,POINT (241380 6712059),POINT (241380 6712059),Katariinan koulu,"Kirkkotie 31, 20540 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
31,POINT (241281 6710562),POINT (241281 6710562),"Kiinamyllyn koulu, Datacityn yksikkö","Lemminkäisenkatu 18 C, 20520 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus"
23,POINT (240310 6709718),POINT (240310 6709718),"Kiinamyllyn koulu, nuorisopsykiatrian yksikkö","Kunnallissairaalantie 20, talo 4 B, 2. krs, PL...","Suomenkielinen perusopetus,Oppilaanohjaus"
12,POINT (239406 6715041),POINT (239406 6715041),"Luolavuoren koulu, Piiparinpolun yksikkö","Piiparinpolku 3, 20360 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
41,POINT (244708 6708507),POINT (244708 6708507),"Luolavuoren koulu, Raadinkadun yksikkö, Lauste...","Raadinkatu 7, D-rak., 20750 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
30,POINT (241211 6708557),POINT (241211 6708557),"Luolavuoren koulu, Ruiskadun yksikkö (pienluok...","Ruiskatu 8, 20720 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
27,POINT (240700 6710724),POINT (240700 6710724),"Luostarivuoren koulu, Kerttulin yksikkö","Kellonsoittajankatu 6, 20500 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
19,POINT (239871 6710362),POINT (239871 6710362),"Luostarivuoren koulu, Luostarivuoren yksikkö","Luostarinkatu 13, 20700 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
11,POINT (239309 6709910),POINT (239309 6709910),"Luostarivuoren koulu, Martin yksikkö","Hopeasepänkuja 2, 20810 TURKU","Perusopetuksen erikoisluokat,Suomenkielinen pe..."
20,POINT (239933 6709748),POINT (239933 6709748),"Mikaelin koulu, Jopo-yksikkö, Mikaelin koulu, ...","Luolavuorentie 1A, 20810 TURKU","Oppilaanohjaus,Joustava perusopetus (JOPO)"
9,POINT (238990 6710649),POINT (238990 6710649),"Mikaelin koulu, Koulukadun yksikkö","Koulukatu 8, 20100 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
34,POINT (241497 6712112),POINT (241497 6712112),"Nummenpakan koulu, Aurajoen yksikkö","Papinkatu 4, 20540 TURKU","Henkilökohtainen taideohjaus,Suomenkielinen pe..."
37,POINT (242567 6713017),POINT (242567 6713017),"Nummenpakan koulu, Halisten yksikkö, Nummenpak...","Paavinkatu 13, 20540 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
0,POINT (234346 6711304),POINT (234346 6711304),Pansion koulu,"Pernontie 29, 20240 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
16,POINT (239632 6711361),POINT (239632 6711361),"Puolalan koulu, Kauppiaskadun yksikkö","Kauppiaskatu 14, 20100 TURKU","Perusopetuksen erikoisluokat,Suomenkielinen pe..."
13,POINT (239424 6711207),POINT (239424 6711207),"Puolalan koulu, Puutarhakadun yksikkö","Puutarhakatu 5, 20100 TURKU","Perusopetuksen erikoisluokat,Suomenkielinen pe..."
21,POINT (239950 6709886),POINT (239950 6709886),Puropellon koulu,"Sepänkatu 11, 20700 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
39,POINT (243495 6709983),POINT (243495 6709983),Pääskyvuoren koulu,"Talvitie 10, 20610 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
6,POINT (238715 6711763),POINT (238715 6711763),"Raunistulan koulu, Kähärin yksikkö","Pietari Valdin katu 14, 20100 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
17,POINT (239740 6712307),POINT (239740 6712307),"Raunistulan koulu, Raunistulan yksikkö","Oikotie 1, 20300 TURKU","Perusopetuksen erikoisluokat,Suomenkielinen pe..."
14,POINT (239428 6712751),POINT (239428 6712751),Rieskalähteen koulu,"Jöllintie 3, 20300 TURKU","Henkilökohtainen taideohjaus,Perusopetuksen er..."
18,POINT (239805 6710221),POINT (239805 6710221),S:t Olofsskolan,"Sirkkalankatu 39, 20700 TURKU","Perusopetuksen erikoisluokat,Ruotsinkielinen p..."
25,POINT (240530 6710393),POINT (240530 6710393),Sirkkala skola,"Sirkkalankatu 20, 20700 TURKU",Ruotsinkielinen perusopetus
4,POINT (237931 6713286),POINT (237931 6713286),"Teräsrautelan koulu, Suikkilan yksikkö, Teräsr...","Korkkisvuorenkatu 14, 20320 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
5,POINT (238090 6710020),POINT (238090 6710020),Topeliuksen koulu,"Pakkarinkatu 10, 20100 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
29,POINT (241119 6714372),POINT (241119 6714372),"Turun Lyseon koulu, Kärsämäen yksikkö","Kärsämäentie 46, 20360 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
26,POINT (240551 6714563),POINT (240551 6714563),"Turun Lyseon koulu, Pallivahan yksikkö","Paltankatu 4, 20360 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
22,POINT (240177 6715471),POINT (240177 6715471),"Turun Lyseon koulu, Runosmäen yksikkö, Mikaeli...","Varusmestarintie 19, 20360 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
42,POINT (244762 6710036),POINT (244762 6710036),Varissuon koulu,"Kuopuksenpolku , 20520 TURKU","Suomenkielinen perusopetus,Perusopetukseen val..."
32,POINT (241305 6709342),POINT (241305 6709342),"Vasaramäen koulu, Lehmustien yksikkö","Lehmustie 7, 20720 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
35,POINT (241523 6710521),POINT (241523 6710521),"Vasaramäen koulu, Lemminkäisenkadun yksikkö","Lemminkäisenkatu 30, 3 krs., 20520 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
36,POINT (241685 6709840),POINT (241685 6709840),"Vasaramäen koulu, Puistokoulun yksikkö","Puolukkatie 11, 20720 TURKU","Suomenkielinen perusopetus,Oppilaanohjaus,Peru..."
10,POINT (239162 6707988),POINT (239162 6707988),"Vähä-Heikkilän koulu, Uittamon yksikkö","Jalustinkatu 8, 20880 TURKU","Suomenkielinen perusopetus,Perusopetuksen aamu..."
8,POINT (238890 6709130),POINT (238890 6709130),"Vähä-Heikkilän koulu, Vähä-Heikkilän yksikkö","Myllymäentie 42, 20810 TURKU","Perusopetuksen erikoisluokat,Suomenkielinen pe..."
3,POINT (237111 6706735),POINT (237111 6706735),Wäinö Aaltosen koulu,"Wäinö Aaltosen koulutie 3, 20900 TURKU","Perusopetuksen erikoisluokat,Suomenkielinen pe..."

In [10]:
schools_combined.to_file(OUTPUT_DIRECTORY / "turku_schools.gpkg")